### ISSUE TITLE
Non-standard output in XML files

### ISSUE THREAD

**Issue by Biotronic** [jugglingcats/tachograph-reader#46]
The XML files created by this tool contain data in some non-standard formats (datetime not ISO-8601, bools not all-lowercase, and time without seconds). This contrasts with XSD formats:

https://www.w3schools.com/xml/schema_dtypes_misc.asp (bools)
https://www.w3schools.com/xml/schema_dtypes_date.asp (time and datetime)

**Comment by jugglingcats** [comment]
This is unlikely to be changed as it would impact all existing downstream tools, sorry.

**Comment by davispuh** [comment]
Not necessarily, there could be flag to generate more compliant XML format (so that existing programs use current format and new programs could use this new format), but it's not something I'm interested in (for me it doesn't matter if there is such option or not), I'm actually interested in not generating XML at all and using parsed data directly as I wrote about it in https://github.com/jugglingcats/tachograph-reader/issues/13#issuecomment-306484927
