### ISSUE TITLE
TimeZone problem

### ISSUE THREAD

**Issue by ramasofficial** [jugglingcats/tachograph-reader#54]
Hello,

We are in different time zone and we need to change all dates from UTC to GMT. How we need to do it?

Example:
![image](https://user-images.githubusercontent.com/36000935/76861145-ca673080-6864-11ea-9dad-d6b86acfa2cf.png)
All times need to add 2 hours...
Do this code have a solution or configuration file with this problem?

Thank you!

**Comment by jugglingcats** [comment]
Hi @ramasofficial, as far as I can tell the spec does not discuss or support time zones at all. There are two pieces of info in the example you gave:

The `CardActivityDailyRecord.DateTime` attribute. This is using a `TimeReal` data type which is defined (in section 2.110) as seconds since epoch (1 Jan 1970). *However* in section 2.5 for `CardActivityDailyRecord` this field is described as 'the date of the record'. Therefore I would expect it always to have 00:00:00 as the time component.

The `ActivityChangeInfo.Time` attribute. This is defined (section 2.1) as seconds since midnight on the given day.

Since neither of these has support for timezone, times must be set by the VU and be one of:
a) UTC always
b) in the timezone the vehicle unit is set to (presumably the country of origin)
c) in the local timezone (which could be really confusing as trucks move between timezones!)

You said you want times in GMT, but this _is UTC_ if you are not concerned with daylight saving. Therefore you should have no work to do.

I would hope that vehicle units always record in UTC and you can then convert to whatever local timezone you need, but I cannot say for sure that is how it works. Option c seems very unlikely though.

My guess is you want to treat all date/times as UTC and convert downstream to a local time (eg. if you want to show midnight on 1 July as 01:00 because of British summer time, GMT+1).

Hope it helps, sorry for the ramble!

**Comment by ramasofficial** [comment]
Yes we need to add 2 hours to all ActivityChangeInfo records. Do you have a minds how to do it?

**Comment by ramasofficial** [comment]
I want to convert in Lithuanian time GMT+2, but then records move to next day and i not have minds how to solve it

**Comment by jugglingcats** [comment]
tachograph-reader just extracts the information in the vehicle/driver files, using the structure in the spec. It sounds like you want to post-process this data to put in your local timezone. Consider what you will have to do when going in and out of daylight saving (summer time)! You will have to add your own business logic. I think this is beyond the scope of tachograph-reader itself, sorry.

**Comment by mpi-wl** [comment]
Tachographs always record a coordinated universal date and time (UTC).
That's what the regulations say.

In the tachograph, the driver can change the local time - but this is only the time on the display. In fact, this time is recorded according to UTC.

This project reads raw data from ddd files. You need a program to analyze this data (display, check for violations, etc.).
In some situations you should check by UTC time (for example, the length of the activity when changing to summer / winter time may have a different value), and in other situations by local time (for example, driving time per week).
Data should be analyzed according to the local time in the country in which the car was registered.

> The `CardActivityDailyRecord.DateTime` attribute. This is using a `TimeReal` data type which is defined (in section 2.110) as seconds since epoch (1 Jan 1970). _However_ in section 2.5 for `CardActivityDailyRecord` this field is described as 'the date of the record'. Therefore I would expect it always to have 00:00:00 as the time component.

I have not seen ddd files from the driver card in which it would be different, but ... in files from tachographs in [76 02 / 76 22].timeReal contains the time 23:59:59 (VDO) or 00:00:00 (Stoneridge). Therefore, to be sure, you should set the time yourself to 00:00:00
